spring:
  application:
    name: test***
  datasource:
    username: test***
    password: test***
    url: jdbc:postgresql://localhost:5432/***
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  token: test***